### ISSUE TITLE
svg-icon-sets

### ISSUE THREAD

**Issue by annadecarle** [annadecarle/svg-icon-sets#1]
@thatkidmadrid

Hi Christian,

I'm having trouble with getting my .svg's to appear on my website. I've tried trouble shooting but nothing seems to get them to appear. I'm also having trouble with my background gradient, as I can't get it to stop repeating. Would you be able to help me? 

Thanks, 
Anna DeCarle
Web Design– Group 2

  <section>
      <i class="icon">
        <svg><use xlink:href="images/sprite-sheet.svg#space-bubbles"/></svg></i>
        <h2>Space bubbles</h2>
        <h3>Space bubbled buildings will house large green houses and natural habitats so Earth-borne life can live on Mars.</h3>
        <a href="#">Learn about space bubbles</a>
      </section>

      <section>
        <i class="icon">
          <svg><use xlink:href="sprite-sheet.svg#super-domes"/></svg>
        </i>
        <h2>Super domes</h2>
        <h3>Super domes are the large, climate controlled city habitats that future human beings will live, work and play in.</h3>
        <a href="#">Learn about super domes</a>
      </section>

      <section>
        <i class="icon">
          <svg><use xlink:href="sprite-sheet.svg#mecha-stilts"/></svg>
        </i>
        <h2>Mecha-stilts</h2>
        <h3>Mecha-stilts are primarily used for science and research—the builds are mobile and self-contained for the most versatility.</h3>
        <a href="#">Learn about mecha-stilts</a>
      </section>

**Comment by thatkidmadrid** [comment]
Hey Anna, pay close attention to the path to the file you're referencing in your `xlink:href`s. I notice the first is properly pointing to the file in the images folder, while the opther two are just pointing to the file from the root of your project. Adding the images folder should help here.

On that note, while looking at your svg i did notice that you're using fills, which I don't think is necessary. Try following the steps as the dinosaur icons walkthrough. save the icons just with black fills, then go in and change the colour with your css. This should make things a lot easier and have things behave as intended.

You can add the css property `background-repeat: no-repeat` to prevent the background from repeating. But I think an even cleaner solution would be to wrap the contents in a wrapper, then apply the background to the wrapper instead of the body. In the solution I have they're using a `<section>` tag, but other tags could be used to do the same thing.

**Comment by annadecarle** [comment]
Okay thanks for your help, i'm going to make those changes.
